FROM python:3.11

WORKDIR /dashboard

COPY ./dashboard /dashboard

RUN pip install --no-cache-dir streamlit plotly psycopg2 pandas sqlalchemy

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
