name: ovos-opendata
services:
  ovos-opendata-api:
    build: .
    container_name: ovos-opendata-api
    image: ovos-opendata/api
    restart: unless-stopped
    ports:
      - "8007:8000"
    env_file: .env
    depends_on:
      - ovos-opendata-db

  ovos-opendata-db:
    image: postgres:18
    container_name: ovos-opendata-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - ~/.local/share/ovos-opendata:/var/lib/postgresql/data
