name: ovos-opendata
services:
  ovos-opendata-api:
    build: .
    container_name: ovos-opendata-api
    image: ovos-opendata/api
    restart: unless-stopped
    ports:
      - "8007:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@ovos-opendata-db:5432/ovos_metrics
    depends_on:
      - ovos-opendata-db

  ovos-opendata-db:
    image: postgres:latest
    container_name: ovos-opendata-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ovos_metrics
    volumes:
      - ~/.local/share/ovos-opendata:/var/lib/postgresql/data

  ovos-opendata-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: ovos-opendata-dashboard
    image: ovos-opendata/dashboard
    restart: unless-stopped
    ports:
      - "8502:8501"
    depends_on:
      - ovos-opendata-api
      - ovos-opendata-db
    environment:
      - DATABASE_URL=postgresql://postgres:password@ovos-opendata-db:5432/ovos_metrics
